### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by DocBrown101** [jpbriquet/docker-decred#3]
Both commands:
docker exec -it dcrwallet dcrctl --wallet getstakeinfo
docker exec -it dcrwallet dcrctl --wallet getvotechoices

results in 401 Unauthorized.

**Comment by jpbriquet** [comment]
Sorry for the late reply, I have just seen your issue today.
Have you find out the root cause ? This kind of error is usually link to wrong credentials or certificates. 
Without logs I cannot help more.
